FROM ubuntu:latest

# Use root user
USER root

# ENV variables
ARG USERNAME=jinx
ARG PASSWORD=powder
# Set the JMeter version
ENV JMETER_VERSION=5.6.3
ENV JMETER_HOME=/opt/apache-jmeter-${JMETER_VERSION}
# Add JMeter to the PATH
ENV PATH=${JMETER_HOME}/bin:$PATH

# Install required packages
RUN apt-get update && \
    apt-get install -y \
    openssh-server \
    sudo \
    openjdk-17-jdk \
    openjdk-17-jre \
    python3 \
    python3-pip \
    python3-pytest \
    python3-flask \
    python3-flake8 \
    python3-bandit \
    git

# Create the user, set the password, and add to sudo group
RUN useradd -ms /bin/bash ${USERNAME} \
    && echo "${USERNAME}:${PASSWORD}" | chpasswd \
    && usermod -aG sudo ${USERNAME} \
    && echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Set up directories and permissions
RUN mkdir -p /home/${USERNAME}/.ssh \
    && chmod 700 /home/${USERNAME}/.ssh

# Ensure known_hosts file exists before applying chmod
RUN touch /home/${USERNAME}/.ssh/known_hosts && \
    chmod 600 /home/${USERNAME}/.ssh/known_hosts

# Expose SSH port
EXPOSE 22

# Start SSH service and keep container running
CMD ["sh", "-c", "sudo service ssh start && tail -f /dev/null"]
